version: '3.8'

services:
  icelandic-voice:
    build: .
    env_file: .env
    volumes:
      - podcast_data:/app/podcast_output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    shm_size: 40g
    healthcheck:
      test: ["CMD-SHELL", "nvidia-smi && test -f /app/podcast_output/healthcheck.ok"]
      interval: 60s
      timeout: 30s
      retries: 3
    restart: unless-stopped

volumes:
  podcast_data: