[phases.setup]
nixPkgs = [
  "python311",
  "nodejs_20",
  "npm",
  "git",
  "ffmpeg",
  "nodejs",
  "gcc",
  "pkg-config"
]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt",
  "npm install -g @leon-ai/cli",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "python webui.py"

[variables]
PYTHON_VERSION = "3.11.7"
NODE_VERSION = "20.x"
NPM_VERSION = "10.x"