[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "ffmpeg",
  "nodejs",
  "npm",
  "git",
  "gcc",
  "pkg-config",
  "openssl"
]

[phases.install]
cmds = [
  "python3 -m pip install --user --upgrade pip",
  "python3 -m pip install --user -r requirements.txt",
  "chmod +x master-setup-script.sh",
  "./master-setup-script.sh"
]

[start]
cmd = "python3 webui.py"

[variables]
PYTHONUNBUFFERED = "1"
PATH = "${PATH}:${HOME}/.local/bin"
PYTHONPATH = "${PWD}"