[phases.setup]
nixPkgs = [
  "python311",
  "nodejs_20",
  "git",
  "ffmpeg",
  "gcc",
  "pkg-config"
]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt",
  "npm install",
  "npm install -g @leon-ai/cli"
]

[phases.build]
cmds = [
  "npm run build",
  "python -m pytest"
]

[start]
cmd = "python webui.py"

[variables]
PYTHONPATH = "${PWD}"