[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = [
  "python311",
  "nodejs_20",
  "git",
  "ffmpeg",
  "gcc",
  "pkg-config",
  "python311Packages.pip",
  "python311Packages.virtualenv"
]

[phases.install]
cmds = [
  "python -m virtualenv .venv",
  ".venv/bin/pip install --upgrade pip",
  ".venv/bin/pip install -r requirements.txt",
  "npm install",
  "npm install -g @leon-ai/cli"
]

[phases.build]
cmds = [
  "npm run build",
  ".venv/bin/python -m pytest"
]

[start]
cmd = ".venv/bin/python webui.py"

[variables]
PYTHONPATH = "${PYTHONPATH}:${PWD}"
VIRTUAL_ENV = "${PWD}/.venv"
PATH = "${VIRTUAL_ENV}/bin:${PATH}"