[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "nodejs_20",
  "git",
  "ffmpeg",
  "gcc",
  "pkg-config"
]

[phases.install]
aptPkgs = [
  "python3-pip"
]
cmds = [
  "python3 -m pip install --user --upgrade pip",
  "python3 -m pip install --user -r requirements.txt",
  "npm install",
  "npm install -g @leon-ai/cli"
]

[phases.build]
cmds = [
  "npm run build",
  "python3 -m pytest"
]

[start]
cmd = "python3 webui.py"

[variables]
PATH = "${PATH}:${HOME}/.local/bin"
PYTHONPATH = "${PWD}"