name: Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          python -m pytest
          
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nixpacks
        run: curl -sSL https://nixpacks.com/install.sh | bash
      
      - name: Build with Nixpacks
        run: nixpacks build . --name halloisland
        
      # Add your deployment steps here
      # For example, if deploying to a cloud platform:
      # - name: Deploy to Platform
      #   run: |
      #     # Add deployment commands
      #   env:
      #     PLATFORM_TOKEN: ${{ secrets.PLATFORM_TOKEN }}

permissions:
  contents: read